
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/docket_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true