
spring:
  config:
    activate:
      on-profile:
        - docker

  datasource:
    url: jdbc:mysql://mysqldb:3306/docket_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true